# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensinopage',
            name='page',
        ),
        migrations.AddField(
            model_name='ensinopage',
            name='pages',
            field=models.ManyToManyField(blank=True, to='ensino.Ensino'),
        ),
    ]
