# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0004_auto_20160916_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensino',
            name='link',
            field=models.CharField(default=2, max_length=3, verbose_name='Caso -1 vai para questoes'),
        ),
        migrations.AlterField(
            model_name='ensino',
            name='number',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
