# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0005_auto_20160916_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensino',
            name='name',
            field=models.CharField(choices=[('central', 'Central'), ('posicao', 'Posicao'), ('variancia', 'Variancia'), ('graficos', 'Graficos'), ('regressao', 'Regressao')], max_length=200),
        ),
    ]
