# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0006_auto_20160916_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='linkVolta',
            field=models.CharField(default=2, max_length=3, verbose_name='Caso -1 vai para questoes'),
        ),
    ]
