# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=1000)),
                ('resposta1', models.CharField(max_length=1000)),
                ('resposta2', models.CharField(max_length=1000)),
                ('resposta3', models.CharField(max_length=1000)),
                ('resposta4', models.CharField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
    ]
