# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(max_length=2)),
                ('dois', models.CharField(max_length=2)),
                ('tres', models.CharField(max_length=2)),
                ('quatro', models.CharField(max_length=2)),
                ('cinco', models.CharField(max_length=2)),
            ],
        ),
    ]
