# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0002_auto_20160915_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensinopage',
            name='pages',
        ),
        migrations.DeleteModel(
            name='ensinoPage',
        ),
    ]
