# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0003_auto_20160915_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ensino',
            name='title',
            field=models.CharField(default='titulo', max_length=400),
        ),
    ]
